spring.application.name=student-management-system
spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
jwt.secret=ThisIsMySuperSecretKeyForJwtAuthentication123456789012345
jwt.expiration=3600000